Added filters by location + Added Central option for location
claudiachua/sps-team3-project pull request #10
Opened 2020-07-19 14:00 UTC by hhjoel

- Added an additional location "Central" for location
- Added the ability for users to filter by different location
- Use case: users might want to filter restaurant recommendations by locations and so we add this feature here
- Setting multiple filters is done wrongly in GroupServlet

2020-07-20 10:33 UTC, HeHaowei requested changes
I think you accidentally change the "group" to "goup", please check with it. Other parts are quite good, LGTM + 1!

2020-07-20 10:33 UTC, HeHaowei commented on friendly/src/main/webapp/index.html
> +            <select id="goups-list"></select>
Why you change it to goups-list?

2020-07-21 10:47 UTC, hhjoel commented on friendly/src/main/webapp/index.html
> +            <select id="goups-list"></select>
Done!

2020-07-21 10:58 UTC, HeHaowei approved these changes
LGTM + 1!

2020-07-21 11:30 UTC, merged